### ISSUE TITLE
Preconfigure PKE in pre-cached images

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/pke#98]
**Is your feature request related to a problem? Please describe.**
When creating a cluster using a pre-cached image with PKE already installed, I don't want:

- PKE to be installed again
- Container runtime and Kubernetes installed again
- Container runtime and Kubernetes configured again

**Describe the solution you'd like to see**
Store some PKE configuration in images that PKE can use to configure the node (eg. container runtime). This configuration could be created by a user data script on base images without PKE.

**Comment by sagikazarmark** [comment]
Config (eg. `/etc/banzaicloud/pke.yaml`):

```yaml
kubernetes:
    version: 1.18.2
    installed: true

containerRuntime:
    type: docker
    installed: true
```

Machine image: generate config
User data script: generate config if not already present
PKE command: do not use the above flags
